name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set DB_PASSWORD
        run: echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: Start containers 
        run: docker-compose -f "docker-compose.yml" up -d 

      - name: Wait for services
        run: sleep 10

      - name: Test frontend
        run: curl -f http://localhost:8080 || exit 1

      - name: Test backend
        run: docker-compose exec -T frontend curl -f http://backend:3000 || exit 1

      - name: Test DB Connection
        run: docker-compose exec -T backend npm test

      - name: Stop containers
        run: docker-compose down -v


  deploy:
    runs-on: ubuntu-latest
    needs: test 
    env:
      AWS_REGION: us-east-1

    strategy:
      matrix:
        service: [frontend, backend, db]

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push frontend inage to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: my-repo
          IMAGE_TAG: ${{ matrix.service }}-${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG ./${{ matrix.service }}/.
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
      
