name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    

    steps:
      - uses: actions/checkout@v4

      - name: Set DB_PASSWORD
        run: echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV

      - name: Start containers
        uses: hoverkraft-tech/compose-action@v2.0.2
        with:
          files: docker-compose.yml
          up: true

      - name: Wait for services
        run: sleep 10

      - name: Test frontend
        run: curl -f http://localhost:8080 || exit 1

      - name: Test backend
        run: docker-compose exec -T frontend curl -f http://backend:3000 || exit 1

      - name: Test DB Connection
        run: docker-compose exec -T backend npm test

      - name: Stop containers
        uses: hoverkraft-tech/compose-action@v2.0.2
        with:
          files: docker-compose.yml
          up: down

  deploy:
    runs-on: ubuntu-latest
    needs: test 
    env:
      AWS_REGION: us-east-1

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Authenticate Docker with ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Build frontend image
        run: |
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/my-repo:frontend-${{ github.sha }} ./frontend/.

      - name: Build backend image
        run: |
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/my-repo:backend-${{ github.sha }} ./backend/.

      - name: Build db image
        run: |
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/my-repo:db-${{ github.sha }} ./db/.

      - name: Push Docker images to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/my-repo:frontend-${{ github.sha }}
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/my-repo:backend-${{ github.sha }}
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/my-repo:db-${{ github.sha }}
